app/Album.php
app/Artist.php
app/Http/Controllers/Api/ArtistController.php
app/Http/Resources/AlbumResource.php
app/Http/Resources/ArtistResource.php
app/Http/Resources/FlacFileResource.php
app/Http/Resources/LabelResource.php
app/Http/Resources/ProfileResource.php
app/Http/Resources/SkuResource.php
app/Http/Resources/SongResource.php
app/Http/Resources/UserResource.php
database/factories/ArtistFactory.php
grumphp.yml
tests/Feature/Controllers/ArtistControllerTest.php
tests/Feature/Repositories/AlbumRepositoryTest.php
tests/Feature/Repositories/SongRepositoryTest.php

Added  `ArtistsResource`  to replace `CatalogResource` in `ArtistController` and any other resources that needed to be associated with the Artist Resource.
This is a step forward on issue #13 
The reason for this PR is to get this branch cleaned and setup for the rest of the WIP API Resources.
It kind of became a "catch all"

Add Artist Resource and related resources

---

grumphp.yml

There was several things wrong with the previous version of this. It
should now be fixed with this commit.

fix(GrumPHP): Update commit message regex pattern

---

grumphp.yml

style: Disable Grum ASCII art

---

app/Http/Resources/AccountResource.php
app/Http/Resources/AlbumResource.php
app/Http/Resources/CountryResource.php
app/Http/Resources/FlacFileResource.php
app/Http/Resources/LabelResource.php
app/Http/Resources/SkuResource.php
routes/api.php

This PR addresses the basic api resource response structures. These may need to adapt as we figure out the rest of the api. This is a good place to start.

Api Resources

---

app/Contracts/UserRepositoryInterface.php
app/Http/Controllers/Api/AlbumController.php
app/Http/Controllers/Api/ArtistController.php
app/Http/Controllers/Api/FlacFileController.php
app/Http/Controllers/Api/SkuController.php
app/Http/Controllers/Api/SongController.php
app/Http/Controllers/Api/UserController.php
routes/api.php

WIP Do not merge ... Will update when ready
This PR should bring all controllers and controller tests up to date!

WIP Api Controllers and Tests

---

CONTRIBUTING.md

Update contributing file to include new documentation references

---

composer.json
composer.lock
grumphp.yml

This PR allows us to use the forked repository that I am maintaining to bring in new features while we wait for the upstream repository to merge my PR's.
Refs:
https://github.com/phpro/grumphp/pull/541
https://github.com/phpro/grumphp/pull/540
https://github.com/phpro/grumphp/pull/539

Use GrumPHP Forked Repository

---

app/Http/Controllers/Api/AlbumController.php
app/Http/Controllers/Api/FlacFileController.php
app/Http/Controllers/Api/GenreController.php
app/Http/Controllers/Api/LabelController.php
app/Http/Controllers/Api/SkuController.php
app/Http/Controllers/Api/SongController.php
app/Http/Controllers/Api/UserController.php
app/Http/Requests/StoreAlbum.php
app/Http/Requests/StoreFlacFile.php
app/Http/Requests/StoreGenre.php
app/Http/Requests/StoreLabel.php
app/Http/Requests/StoreSku.php
app/Http/Requests/StoreSong.php
app/Http/Requests/UpdateAlbum.php
app/Http/Requests/UpdateFlacFile.php
app/Http/Requests/UpdateGenre.php
app/Http/Requests/UpdateLabel.php
app/Http/Requests/UpdateSku.php
app/Http/Requests/UpdateSong.php
app/Http/Resources/GenreResource.php

In consideration to PR #75 
The `Resources` and `Requests` in this commit were only added to satisfy this PR. They will need to be updated appropriately in another PR.
Closes #64 
Closes #65 
Closes #66
Closes #67

Refactor controllers and Add missing controllers with components

---

app/Repositories/AccountRepository.php
app/Repositories/AlbumRepository.php
app/Repositories/ArtistRepository.php
app/Repositories/BaseRepository.php
app/Repositories/CatalogEntityRepository.php
app/Repositories/CrudRepository.php
app/Repositories/FlacFileRepository.php
app/Repositories/GenreRepository.php
app/Repositories/LabelRepository.php
app/Repositories/ProfileRepository.php
app/Repositories/SkuRepository.php
app/Repositories/SongRepository.php
app/Repositories/UserRepository.php
app/Traits/IsProfilable.php
tests/Feature/Repositories/AccountRepositoryTest.php
tests/Feature/Repositories/ArtistRepositoryTest.php
tests/Feature/Repositories/CatalogEntityRepositoryTest.php
tests/Feature/Repositories/LabelRepositoryTest.php
tests/Feature/Repositories/ProfileRepositoryTest.php
tests/Feature/Repositories/UserRepositoryTest.php

Just doing a bit of cleanup here ... while creating a more elegant inheritance flow

Refactor some code while abstracting other

---

app/Providers/ApiRouteServiceProvider.php

Remove FlacFile and Sku routes due to removing the controllers

---

app/Repositories/BaseRepository.php

Pagination can work in a couple different ways.
Crude Examples:
```php
$this->artist->all(10);
// or
$this->artist->model()->where('id', '>', 50)->paginate(10);
```
Closes #86

Add pagination to all() method

---

database/factories/Order.php
database/migrations/2018_09_30_000051_create_orders_table.php
database/migrations/2099_12_31_000000_add_all_foreign_keys.php

refact: Remove uuid in favor of user_id on the Order model

---

tests/Feature/Repositories/AccountRepositoryTest.php
tests/Feature/Repositories/AlbumRepositoryTest.php
tests/Feature/Repositories/ArtistRepositoryTest.php
tests/Feature/Repositories/CatalogEntityRepositoryTest.php
tests/Feature/Repositories/FlacFileRepositoryTest.php
tests/Feature/Repositories/GenreRepositoryTest.php
tests/Feature/Repositories/LabelRepositoryTest.php
tests/Feature/Repositories/OrderItemRepositoryTest.php
tests/Feature/Repositories/OrderRepositoryTest.php
tests/Feature/Repositories/ProfileRepositoryTest.php
tests/Feature/Repositories/RepositoryCrudTestCase.php
tests/Feature/Repositories/RepositoryReadonlyTestCase.php
tests/Feature/Repositories/SongRepositoryTest.php
tests/Feature/Repositories/UserRepositoryTest.php

Fix lingering issues with Repository tests

---

app/Artist.php
app/Console/Commands/Feature.php
app/Contracts/FeaturableModelInterface.php
app/Contracts/FeaturableRepositoryInterface.php
app/Contracts/FeaturedRepositoryInterface.php
app/Featured.php
app/Http/Controllers/Api/FeaturedController.php
app/Http/Requests/StoreFeature.php
app/Http/Requests/UpdateFeature.php
app/Http/Resources/FeaturedResource.php
app/Providers/ApiRouteServiceProvider.php
app/Providers/AppServiceProvider.php
app/Repositories/ArtistRepository.php
app/Repositories/FeaturedRepository.php
config/ihd.featured.php
config/indiehd.featured.php
database/factories/ArtistFactory.php
database/factories/FeaturedFactory.php
database/migrations/2019_05_13_163230_create_featureds_table.php
database/seeds/DatabaseSeeder.php
database/seeds/FeaturedSeeder.php
tests/Feature/Controllers/ArtistControllerTest.php
tests/Feature/Controllers/FeaturedControllerTest.php
tests/Feature/Featured/FeaturedArtisanCommandTest.php
tests/Feature/Featured/FeaturedArtistEligibilityTest.php
tests/Feature/FeaturedArtistTest.php
tests/Feature/Repositories/FeatureRepositoryTest.php

Featured Artists

---

app/Http/Controllers/Api/FeaturedController.php
app/Http/Requests/DestroyFeatured.php
app/Http/Requests/StoreFeatured.php
app/Http/Requests/UpdateFeatured.php

Also, fix incorrect file name.

Fix missing Featured Resource imports

---

app/Providers/ApiRouteServiceProvider.php
app/Services/ApiRoute.php
grumphp.yml
tests/Feature/Services/ApiRouteTest.php

* **New API Route**:
```php
$this->apiRoute($prefix, $controller)
```
* **Defaults and No Additional (with optional exceptions)**:
```php
->addDefaults(array $excepts = []);
```
* **Defaults With EXCEPTIONS**:
```php
->except(array $routes = []);
```
* **ONLY from Defaults**:
```php
->only(array $routes = []);
```
* **Add Custom Route**:
```php
->add($uri, $controllerMethod, $httpMethod = 'get', $name = null)
```

Feature: ApiRoute improvements and API Changes

---

app/Artist.php
app/Repositories/AlbumRepository.php
database/factories/AlbumFactory.php
database/seeds/AlbumsSeeder.php
tests/Feature/Controllers/AlbumControllerTest.php
tests/Feature/Controllers/OrderControllerTest.php
tests/Feature/Featured/FeaturedArtisanCommandTest.php
tests/Feature/Featured/FeaturedArtistEligibilityTest.php
tests/Feature/Repositories/AlbumRepositoryTest.php
tests/Feature/Repositories/ArtistRepositoryTest.php
tests/Feature/Repositories/FlacFileRepositoryTest.php
tests/Feature/Repositories/GenreRepositoryTest.php
tests/Feature/Repositories/LabelRepositoryTest.php
tests/Feature/Repositories/OrderItemRepositoryTest.php
tests/Feature/Repositories/OrderRepositoryTest.php
tests/Feature/Repositories/SongRepositoryTest.php

Tighten-up Album and Song relationship and interaction

---

app/Album.php
app/Casts/Money.php
app/CatalogEntity.php
app/Country.php
app/Featured.php
app/FlacFile.php
app/Http/Requests/StoreAlbum.php
app/Http/Requests/UpdateAlbum.php
app/Http/Resources/AlbumResource.php
app/Profile.php
app/Song.php
composer.json
composer.lock
config/ihd.php
database/factories/AlbumFactory.php
database/factories/SongFactory.php
database/migrations/2017_11_11_000004_create_albums_table.php
database/migrations/2018_01_13_184748_create_songs_table.php
tests/Feature/Casts/MoneyTest.php
tests/Feature/Controllers/AlbumControllerTest.php

When review please check that I've created the correct decimal casts.
`decimal:X` where `X` is the number of digits.
I'm not sure if that means fractional digits. E.g. decimal(15, 2) does that mean X = 15 or X = 2?. 
Do we have any tests that works with models that has decimal types like album or flac file @cbj4074 @poppabear8883 already or should I add a new test to test this?
Tracked it down to this:
```php
protected function asDecimal($value, $decimals)
{
return number_format($value, $decimals, '.', '');
}
```
So it means digits = fractional digits.

refactor: add casts to models

---

.travis.yml

I added the required environment variable to Travis-CI, so once this is merged, I expect that we'll have detailed Codecov data flowing-in.

ci: Add codecov.io script to Travis-CI configuration

---

README.md

Sorry, I meant to update the badge in the previous PR.

ci: Update code coverage badge from Coveralls to Codecov

---

app/Http/Controllers/Api/ApiController.php

refactor: make request validation clearer

---

app/Http/Controllers/Api/AlbumController.php
app/Http/Controllers/Api/ApiController.php
app/Http/Controllers/Api/ArtistController.php
app/Http/Controllers/Api/FeaturedController.php
app/Http/Controllers/Api/GenreController.php
app/Http/Controllers/Api/LabelController.php
app/Http/Controllers/Api/OrderController.php
app/Http/Controllers/Api/SongController.php
app/Http/Controllers/Api/UserController.php
app/Http/Resources/ArtistResource.php
app/Order.php
app/Policies/AlbumPolicy.php
app/Policies/ArtistPolicy.php
app/Policies/FeaturedPolicy.php
app/Policies/GenrePolicy.php
app/Policies/LabelPolicy.php
app/Policies/OrderPolicy.php
app/Policies/SongPolicy.php
app/Policies/UserPolicy.php
app/Providers/AuthServiceProvider.php
tests/Feature/Controllers/AlbumControllerTest.php
tests/Feature/Controllers/ArtistControllerTest.php
tests/Feature/Controllers/Routes/IndexRouteTest.php
tests/Feature/Controllers/UserControllerTest.php

Enable Policies

---

tests/Feature/Featured/FeaturedArtisanCommandTest.php
tests/Feature/Services/ApiRouteTest.php
tests/Feature/Services/MockApiRouteServiceProvider.php

test: fix PSR-4 issues: naming, one-class-per-file

---

database/seeds/OrderSeeder.php

fix: Issue 180

---

app/UuidModel.php
database/migrations/2018_01_13_184726_create_catalog_entities_table.php
database/migrations/2018_09_30_000051_create_orders_table.php

Regarding the changes to CatalogEntity:
https://github.com/indiehd/docs/pull/54/files#diff-dc9c379eb89a3f3ef077d6022453cda7R128-R158
Regarding the changes to Order:
https://github.com/indiehd/docs/pull/54/files#diff-cd044ce09a53bffc6d827b79982a8682R265-R275

fix: Add columns to match requirements elucidated in docs repo

---

app/Providers/AppServiceProvider.php
app/Song.php
composer.lock
database/factories/AlbumFactory.php
database/factories/SongFactory.php
database/migrations/2018_01_13_184748_create_songs_table.php
database/seeders/OrderSeeder.php
database/seeders/StaticDataSeeder.php

This addresses the first part of #192

Remove price references (price handling has been moved into indiehd/velkart repository)
